const PERMISSIONS = {
  VIEW_PUBLIC_ALBUMS: 'VIEW_PUBLIC_ALBUMS',
  VIEW_PROTECTED_ALBUMS: 'VIEW_PROTECTED_ALBUMS',
  UPLOAD_PHOTOS: 'UPLOAD_PHOTOS',
  CREATE_ALBUMS: 'CREATE_ALBUMS',
  EDIT_ALBUMS: 'EDIT_ALBUMS',
  DELETE_ALBUMS: 'DELETE_ALBUMS',
  MOVE_PHOTOS: 'MOVE_PHOTOS',
  DELETE_PHOTOS: 'DELETE_PHOTOS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
};

const PERMISSION_DESCRIPTIONS = {
  VIEW_PUBLIC_ALBUMS: 'Voir les albums publics',
  VIEW_PROTECTED_ALBUMS: 'Voir tous les albums protégés',
  UPLOAD_PHOTOS: 'Importer des photos',
  CREATE_ALBUMS: 'Créer des albums',
  EDIT_ALBUMS: 'Modifier les albums',
  DELETE_ALBUMS: 'Supprimer les albums',
  MOVE_PHOTOS: 'Déplacer des photos',
  DELETE_PHOTOS: 'Supprimer des photos',
  MANAGE_USERS: 'Gérer les utilisateurs',
  MANAGE_PERMISSIONS: 'Gérer les permissions et consulter le journal',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

module.exports = { PERMISSIONS, PERMISSION_DESCRIPTIONS, ALL_PERMISSIONS };
