const PERMISSIONS = {
  VIEW_PUBLIC_ALBUMS: 'VIEW_PUBLIC_ALBUMS',
  VIEW_PROTECTED_ALBUMS: 'VIEW_PROTECTED_ALBUMS',
  UPLOAD_PHOTOS: 'UPLOAD_PHOTOS',
  CREATE_ALBUMS: 'CREATE_ALBUMS',
  EDIT_ALBUMS: 'EDIT_ALBUMS',
  DELETE_ALBUMS: 'DELETE_ALBUMS',
  MOVE_PHOTOS: 'MOVE_PHOTOS',
  DELETE_PHOTOS: 'DELETE_PHOTOS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

module.exports = { PERMISSIONS, ALL_PERMISSIONS };
